#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <sys/stat.h>
#include <sys/mman.h>

int main()
{
    printf("; generated by const.c\n");
    printf("%%define SYS_read %d\n", SYS_read);
    printf("%%define SYS_write %d\n", SYS_write);
    printf("%%define SYS_open %d\n", SYS_open);
    printf("%%define SYS_stat %d\n", SYS_stat);
    printf("%%define SYS_mmap %d\n", SYS_mmap);
    printf("%%define SYS_munmap %d\n", SYS_munmap);
    printf("%%define SYS_exit %d\n", SYS_exit);
    printf("%%define STDIN_FILENO %d\n", STDIN_FILENO);
    printf("%%define STDOUT_FILENO %d\n", STDOUT_FILENO);
    printf("%%define STDERR_FILENO %d\n", STDERR_FILENO);
    printf("%%define EXIT_SUCCESS %d\n", EXIT_SUCCESS);
    printf("%%define EXIT_FAILURE %d\n", EXIT_FAILURE);
    printf("%%define O_RDONLY %d\n", O_RDONLY);
    printf("%%define STAT_SIZE %zu\n", sizeof(struct stat));
    printf("%%define STAT_OFFSET_st_size %zu\n", offsetof(struct stat, st_size));
    printf("%%define PROT_READ %d\n", PROT_READ);
    printf("%%define PROT_WRITE %d\n", PROT_WRITE);
    printf("%%define PROT_EXEC %d\n", PROT_EXEC);
    printf("%%define PAGESIZE %ld\n", sysconf(_SC_PAGESIZE));
    printf("%%define MAP_PRIVATE %d\n", MAP_PRIVATE);
    printf("%%define MAP_ANONYMOUS %d\n", MAP_ANONYMOUS);
}
